use_frameworks!

target 'TestStaticLib2018_Example' do
  pod 'TestStaticLib2018', :path => '../'

  target 'TestStaticLib2018_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
